### ISSUE TITLE
Fix state processing

### ISSUE THREAD

**Issue by emptybutton** [emptybutton/ToDo#26]
The project has accumulated too many problems related to incorrect (not encapsulated) state processing.
To fix this, need to refactor all mutable states to make them immutable.

Refactored immutable code must be impurity safe.

**Comment by TheArtur128** [comment]
As it turns out, adding purity has a cascading nature and for one clean code to work correctly, more clean code is needed. In the context that the entire implementation is mutable and that the requirement for fault tolerance is low, it is necessary to replace the use of `Container`s, which can be thought of as an abstraction over fields (one container as one field), with the use of `Matching`s, which can be thought of as an abstraction for adding fields to other values.
